version: "3.2"

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Sao_Paulo
      LOG_LEVEL: info
      LOG_JSON: "false"
    deploy:
      placement:
        constraints:
          - node.role == manager
