name: ci

on:
  push:
    branches:
      - prod
      - staging

env:
  REGISTRY_URL: YOUR_REGISTRY_URL

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Generate tag name
        shell: bash
        run: |-
          echo "IMAGE_TAG=${{ REGISTRY_URL }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          # target: server  # for multi-stage builds
          push: true
          tags: ${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
