---
- name: Setup Nodes
  hosts: all
  become: true
  # remote_user: ubuntu
  vars:
    local_repo_dir: "{{ playbook_dir }}/.."

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - vim
          - cron
          - apache2-utils
          - rsync
        state: present
        update_cache: true
      environment:
        REMOTE_USER: "{{ ansible_user }}"

    - name: Setup
      register: output
      changed_when: output.rc != 0
      ansible.legacy.shell: |
        curl -fsSL https://get.docker.com | sh - &&
        sudo usermod -aG docker $USER &&
        sudo usermod -aG docker $REMOTE_USER
      environment:
        REMOTE_USER: "{{ ansible_user }}"

    - name: Check if iptables is installed # noqa: no-changed-when
      ansible.builtin.command: systemctl status iptables
      register: iptables_check
      failed_when: false
      become: true

    - name: Stop & Disable iptables
      become: true
      ansible.builtin.systemd_service:
        name: iptables
        state: stopped
        enabled: false
      when: iptables_check.rc == 0
      environment:
        REMOTE_USER: "{{ ansible_user }}"

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
